### PR TITLE
Fix LICENSE.md file to CC-BY-SA, as README.md says

### PR DESCRIPTION
**Pull request by kfogel**
README.md says this repository is under CC-BY-SA, but the LICENSE file
had the text of CC-BY in it.  I'm assuming that README.md is right and
that the LICENSE file content was just an accidental mis-copy
somewhere along the way.  This change switches the license file to
have CC-BY-SA and changes its format to Markdown (and hence the name
from 'LICENSE' to 'LICENSE.md').  The format change is both to match
README.md and to match what seems to be the trend in freely-licensed
projects of using Markdown format for license files.

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @kfogel. This looks good to me (though counter to the trend that you point out GitHub still defaults to plaintext LICENSE files, any thoughts about this discrepancy?)

I would like to request you to include an update to the link in the README that points to the license, since the name changes, the link would break otherwise. I could change it myself if you would open this PR directly on a branch to this repo, but since you are working on a fork, I can't do it so easily.

Thanks!

**Comment by kfogel** [comment]
Good point, @lacabra!  Thanks for noticing -- I should have checked in `README.md` for links.

I've updated the branch via a rebase, so that it's still one commit.

Regarding GitHub's default, I would guess that they're trying to be format-neutral (i.e., treating "plain text" as being not a format choice, whereas choosing Markdown would be pushing a preference for Markdown).  But that's just a guess; I have never asked them about it.

**Comment by kfogel** [comment]
@lacabra And we may switch to working on branches directly in this repository -- that might make more sense.  Let me talk to @jvasile and @amye about it.

**Review by lacabra — APPROVED** [review]
Thanks @kfogel, this looks good to me. Good catch on the license mismatch 🙏

**Pull request merged**
