### PR TITLE
Add "Ecosystem Mapping" section to Adoptability

### PR DESCRIPTION
**Pull request by kfogel**
Rename "Landscape Analysis / Mapping Technical Capacity and Gaps" to
"Ecosystem Mapping for Adoptability" and write the latter, but preface
it with a long tbd comment explaining the decision to rename and
inviting further discussion about that.  Also add two ecosystem map
images, although the new section only uses one of them right now.

Update outline.md accordingly, and add a reference in resources.md to
a post about ecosystem mapping.

### CODE REVIEW

**Comment by kfogel** [comment]
Discussion welcome, on the question raised in the "TBD" note that starts out the diff.

**Comment by sstruble** [comment]
Karl, I agree with your reasoning here for the interpretation and think what you've added is at the right level of depth and flows sensibly. If this direction is agreed upon, I will add a cross-reference in/to the Community + Ecosystem section, b/c ecosystem maps are useful to thinking about archetypes. I think it's good to keep the deeper details to the Appendix, and I can think of a few other resources to add (e.g. although it gets deep into business strategy, wardley maps are a nice way to map the value chain that has to develop in order for a good/service to actually meet users' needs, and it can highlight where commodification would be helpful and thus an open collaborative effort of potential value).

**Comment by sstruble** [comment]
I'd also pull out a Key Recommendation here, which I can add

**Review by lacabra — APPROVED** [review]
The approach presented here makes sense to me, thanks for the detailed explanation @kfogel

**Review by sstruble — APPROVED** [review]

**Review by sstruble — APPROVED** [review]

**Review by amye — APPROVED** [review]

**Comment by kfogel** [comment]
Many thanks, @lacabra, @sstruble, and @amye.  I will remove the TBD comment, merge now, and then @sstruble you can make the Key Recommendation edit as a separate PR.

**Comment by kfogel** [comment]
Okay, done.  @sstruble, please go ahead and make a PR for the follow-on changes you describe above.

**Pull request merged**
