### PR TITLE
Add geonode report to resources

### PR DESCRIPTION
**Pull request by jvasile**

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @jvasile.

My one comment would be to only add resources once: otherwise I find it misleading that we may end up with a long list of resources with several duplicates. So I'd say to choose one category that captures it best, and include it there, but I can be convinced otherwise.

cc: @imahgoub

**Comment by kfogel** [comment]
Is it possible that what really happened here is that the GeoNode report was accidentally added a second time?

I've created PR #9 to fix the title of the original entry.  I think if that PR is merged, then this PR #8 is not necessary.

**Comment by jvasile** [comment]
Agreed.  Thanks, Karl.

**Comment by lacabra** [comment]
Closing as per the comment above, and having merged #9.

**Pull request closed without merging**
